### PR TITLE
Make tests pass: ensure ordering of fixtures.

### PR DESCRIPTION
**Pull request by martinpovolny**
Before this PR the tests would at random fail or succeed. Based on the order in which files with test data are loaded.

Plus some minor cleanups.

@4n4nd : please review.

### CODE REVIEW

**Comment by 4n4nd** [comment]
Thanks @martinpovolny :heart:

**Comment by martinpovolny** [comment]
Hello!

I wonder how you run test.

After adding `httmock` to `tests_require=` in `setup.py` I can run 

`PROM_URL="http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.c
om/"   python setup.py test`

with 4 tests failing.



After installing `pytest` and `httmock` I can use `PROM_URL="http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/"  pytest`

with 4 tests failing.

What is the preferred workflow here? It probably should be documented.

I'd help fix that but we need to know what is the preferred way.

Btw `setup.py test` is going to be deprecated (or is already?) https://github.com/pypa/setuptools/issues/1684

**Comment by martinpovolny** [comment]
"Thoth Bot sesheta" is failing even more than 4 tests because 
```
PROM_URL="http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/"
```
is not set

**Comment by 4n4nd** [comment]
> "Thoth Bot sesheta" is failing even more than 4 tests because
> 
> ```
> PROM_URL="http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/"
> ```
> 
> is not set

Yeah there is an issue open for that (#128) and the Thoth team is working on it

**Comment by 4n4nd** [comment]
> After installing `pytest` and `httmock` I can use `PROM_URL="http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/" pytest`

This is what I do, I think this is also the preferred way to do it.


> Btw `setup.py test` is going to be deprecated (or is already?)

Are we using `python setup.py test` anywhere?

**Comment by martinpovolny** [comment]
@4n4nd : I figured that the failing tests are due to an (incorrect) assumption that the order in which files with test data are loaded is fixed.
So I am adding a patch that ensures this ordering. And the tests should pass now.

Regarding `setup.py test` vs `pytest`. There's no information in the Readme on this. How shall I (anyone) know? Let me add it to the readme.

**Comment by 4n4nd** [comment]
> Regarding setup.py test vs pytest. There's no information in the Readme on this. How shall I (anyone) know? Let me add it to the readme.
Yeah it should be documented. Thanks!

**Comment by martinpovolny** [comment]
Fixes https://github.com/AICoE/prometheus-api-client-python/issues/141 (except for the thoth failure)

**Pull request merged**
