### PR TITLE
method to access prometheus query_range HTTP API

### PR DESCRIPTION
**Pull request by pbadenski**
Fixes: #61 

I didn't include unit tests as I couldn't recreate the test environment, but I did test manually and it worked.

### CODE REVIEW

**Comment by 4n4nd** [comment]
@goern no tests? Who let the bots out?

**Comment by pbadenski** [comment]
I can definitely add tests if you could give me some hints on setting up the test environment 😄

**Comment by 4n4nd** [comment]
So we have a bot that runs a few tests on every new PR, I was just wondering why that didn't work

**Comment by pbadenski** [comment]
Is there anything I should do to speed up merge? I'm waiting for this feature to add functionalities in our system 😄

**Comment by goern** [comment]
recheck

**Comment by pbadenski** [comment]
I can, could you provide me with hints on how to set up testing environment? It looks like prometheus need to be set up and loaded up with some data.

**Comment by 4n4nd** [comment]
oh nvm I think I'll just write it

**Pull request merged**
