### PR TITLE
Updated the pipfile and the requirement.txt file

### PR DESCRIPTION
**Pull request by suppathak**
Update the Pipfile and requirement.txt file to have pandas = ">=1.0.0"

### CODE REVIEW

**Comment by 4n4nd** [comment]
retest

**Comment by 4n4nd** [comment]
regate

**Comment by 4n4nd** [comment]
@harshad16 could you please check why the zuul tests aren't running?

**Comment by harshad16** [comment]
recheck

**Comment by harshad16** [comment]
@4n4nd , seems like infrastructure zuul is running on is having issues, we are trying to move away from zuul, so longer looking into maintaining that , i will open an issue to get aicoe-ci do pytest with the provided env and migrate from zuul.

**Pull request merged**
