### PR TITLE
Add Coala Linter

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Comment by harshad16** [comment]
recheck

**Comment by harshad16** [comment]
recheck

**Comment by harshad16** [comment]
The zuul coala test is fixed. Following errors in README.md is causing coala test to fail. Fix and recheck  please.
```
"Executing section all.md...",
                                "|    | [NORMAL] MarkdownBear:",
                                "|    | The text does not comply to the set style.",
                                "|----|    | /tmp/src/github.com/AICoE/prometheus-api-client-python/README.md",
                                "|    |++++| /tmp/src/github.com/AICoE/prometheus-api-client-python/README.md",
                                "|   1|   1| # prometheus-api-client",
                                "|   2|   2| ",
                                "|   3|    |-[![Codacy Badge](https://api.codacy.com/project/badge/Grade/7d838be9b51e4daaa20be1772f5c9ad2)](https://www.codacy.com/manual/4n4nd/prometheus-api-client-python?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=AICoE/prometheus-api-client-python&amp;utm_campaign=Badge_Grade)",
                                "|    |   3|+[![Codacy Badge](https://api.codacy.com/project/badge/Grade/7d838be9b51e4daaa20be1772f5c9ad2)](https://www.codacy.com/manual/4n4nd/prometheus-api-client-python?utm_source=github.com&utm_medium=referral&utm_content=AICoE/prometheus-api-client-python&utm_campaign=Badge_Grade)",
                                "|   4|   4| ",
                                "|   5|   5| A Python wrapper for the Prometheus http api and some tools for metrics processing.",
                                "|   6|   6| ",
                                "\u001b[34m[INFO]\u001b[0m[19:04:06] Applied 'ShowPatchAction' on 'README.md' from 'MarkdownBear'.\u001b[0m",
                                "|    | [NORMAL] MarkdownBear:",
                                "|    | The text does not comply to the set style.",
                                "|----|    | /tmp/src/github.com/AICoE/prometheus-api-client-python/README.md",
                                "|    |++++| /tmp/src/github.com/AICoE/prometheus-api-client-python/README.md",
                                "|  16|  16| ",
                                "|  17|  17| ## Links",
                                "|  18|  18| ",
                                "|  19|    |-* [Documentation](https://prometheus-api-client-python.readthedocs.io/source/prometheus_api_client.html)",
                                "|    |  19|+- [Documentation](https://prometheus-api-client-python.readthedocs.io/source/prometheus_api_client.html)",
                                "\u001b[34m[INFO]\u001b[0m[19:04:06] Applied 'ShowPatchAction' on 'README.md' from 'MarkdownBear'.\u001b[0m",
                                "|    | [NORMAL] MarkdownBear:",
                                "|    | The text does not comply to the set style.",
                                "|----|    | /tmp/src/github.com/AICoE/prometheus-api-client-python/CHANGELOG.md",
                                "|    |++++| /tmp/src/github.com/AICoE/prometheus-api-client-python/CHANGELOG.md",
                                "|    |   1|+## Release 0.2.1 (2019-10-18T12:38:12)",
                                "|   1|   2| ",
                                "|   2|    |-## Release 0.2.1 (2019-10-18T12:38:12)",
                                "|   3|    |-* Using env var set in zuul config",
                                "|   4|    |-* Revert \"[WIP]Use .zuul.yaml for pytest env vars instead of .env\"",
                                "|   5|    |-* Use .zuul.yaml for pytest env vars instead of .env",
                                "|   6|    |-* Update Version number to create a new release",
                                "|   7|    |-* Initial dependency lock",
                                "|   8|    |-* Add Pipfile for dependency management",
                                "|   9|    |-* Add .env file for prometheus url to run pytest",
                                "|  10|    |-* Update README.md",
                                "|  11|    |-* Add a .coafile And fix coala errors",
                                "|  12|    |-* py linting and coala fixes",
                                "|  13|    |-* Added kebechet support",
                                "|  14|    |-* Delete .stickler.yml",
                                "|  15|    |-* added Thoth's Zuul and Coala config (#44)",
                                "|  16|    |-* Remove matplotlib warning",
                                "|  17|    |-* bump version number to 0.0.2b4 for a new pre-release"
....
```

**Comment by goern** [comment]
is this still valid?

**Comment by 4n4nd** [comment]
LGTM :+1: 
@harshad16 can you please give it a look?

**Pull request merged**
