### PR TITLE
 feat: replaced exit with ValueError

### PR DESCRIPTION
**Pull request by anushkrishnav**
Fixes the Issue: #79

### CODE REVIEW

**Comment by anushkrishnav** [comment]
@4n4nd  or @hemajv  please look into it this :)

**Review by 4n4nd — APPROVED** [review]
LGTM 👍
Thanks!

**Comment by anushkrishnav** [comment]
> LGTM 
> Thanks!

I would love to get more involved into such projects.

**Comment by 4n4nd** [comment]
Hey @anushkrishnav thanks for contributing :+1: 

> I would love to get more involved into such projects.

All the issues in [this org](https://github.com/AICoE) should be open for community contribution. If you have new ideas or suggestions please create new issues for them and when you start working on something, please leave a comment on the issue so that we don't duplicate any efforts.

Let us know if there's something specific that you want to work on.

**Pull request merged**
