### PR TITLE
Mocks for tests

### PR DESCRIPTION
**Pull request by lobziik**
Changes from #72, fixtures/helpers for mocking network and initial structure for separating unittests.

Requires [httmock](https://github.com/patrys/httmock) library.

### CODE REVIEW

**Comment by lobziik** [comment]
I finally found that there is no pytests...

**Comment by 4n4nd** [comment]
you can add it to the dev section of the pipfile, you can see the log for it [here](https://managesf.thoth-station.ninja/logs/77/77/d841c833435b18943e6c24cb9cb43e62f10cd4c4/check/thoth-pytest/52a1cbe/ara-report/result/67ff5d0d-37b0-464c-8199-6498551ded4c/)

**Comment by lobziik** [comment]
> @lobziik you can add it to the dev section of the pipfile, you can see the log for it [here](https://managesf.thoth-station.ninja/logs/77/77/d841c833435b18943e6c24cb9cb43e62f10cd4c4/check/thoth-pytest/52a1cbe/ara-report/result/67ff5d0d-37b0-464c-8199-6498551ded4c/)

Unfortunately, not available from the wild... :D

**Comment by 4n4nd** [comment]
> > @lobziik you can add it to the dev section of the pipfile, you can see the log for it [here](https://managesf.thoth-station.ninja/logs/77/77/d841c833435b18943e6c24cb9cb43e62f10cd4c4/check/thoth-pytest/52a1cbe/ara-report/result/67ff5d0d-37b0-464c-8199-6498551ded4c/)
> 
> Unfortunately, not available from the wild... :D

you cannot see the logs?

**Comment by lobziik** [comment]
> > > @lobziik you can add it to the dev section of the pipfile, you can see the log for it [here](https://managesf.thoth-station.ninja/logs/77/77/d841c833435b18943e6c24cb9cb43e62f10cd4c4/check/thoth-pytest/52a1cbe/ara-report/result/67ff5d0d-37b0-464c-8199-6498551ded4c/)
> > 
> > 
> > Unfortunately, not available from the wild... :D
> 
> you cannot see the logs?

I didn't have vpn on my home machine :)
Btw, I updated #72. Mocks and tests for changes are there. I adopted that for unittest

**Pull request closed without merging**
