### PR TITLE
include aicoe-ci configuration file with pytest env vars

### PR DESCRIPTION
**Pull request by harshad16**
include aicoe-ci configuration file with pytest env vars and remove zuul config.
fixes: #128 
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by harshad16** [comment]
This would fix the pytest check failure due to unavailable env vars, once this PR is merged.

**Comment by harshad16** [comment]
@4n4nd , should I remove the .zuul.yaml file with this PR or do you want another PR for that? As zuul is not helpful anymore for this repository.

**Comment by 4n4nd** [comment]
> @4n4nd , should I remove the .zuul.yaml file with this PR or do you want another PR for that? As zuul is not helpful anymore for this repository.

Could you please delete it in this PR?

**Comment by harshad16** [comment]
> Could you please link a sample pre-commit config?

definitely will do , actually i will open a issue so we could monitor that.

**Pull request merged**
