### PR TITLE
fix of the naming which is causing dependency update failure

### PR DESCRIPTION
**Pull request by harshad16**
fix of the naming which is causing dependency update failure
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Reference: https://github.com/pypa/pipenv/issues/4699

### CODE REVIEW

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by harshad16** [comment]
pytest has network issues, will try to fix it with another pr for ci testing.

**Comment by 4n4nd** [comment]
merging PR since the pytest fails are because of the incorrect prometheus url

**Pull request merged**
