### PR TITLE
[WIP] Add a Metric Class to make metric data processing easier

### PR DESCRIPTION
**Pull request by 4n4nd**

### CODE REVIEW

**Comment by 4n4nd** [comment]
I don't know how to fix the `F401 '.metric.Metric' imported but unused` error, I can change the stickler config to increase the max line length

**Comment by MichaelClifford** [comment]
Look at this stickler config as an example for how to ignore certain error types like `F401`.  https://github.com/AICoE/prometheus-flatliner/blob/master/.stickler.yml

Also, it looks like for other projects that are using the coala linter define the max line length at 120. So we can probably update to that number.

**Comment by 4n4nd** [comment]
So if I ignore F401, it will ignore even the real unused imports

**Comment by MichaelClifford** [comment]
Ok, then that's fine if this F401 is a special case. Once the length is increased. I'll approve.

**Comment by 4n4nd** [comment]
I have no idea why stickler disappeared

**Comment by MichaelClifford** [comment]
LGTM

**Comment by 4n4nd** [comment]
Changed it to WIP found a bug

**Comment by 4n4nd** [comment]
lets start with a nice clean PR

**Pull request closed without merging**
