### PR TITLE
Enable pre-commit checks for the application

### PR DESCRIPTION
**Pull request by harshad16**
Enable pre-commit checks for the application

These changes are for better readability and code maintenance. 
pre-commit would respond with issues comment in the PR if the code are not meet with the standards

Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by martinpovolny** [comment]
All those "noqa" comments are coming from some IDE?

It makes me wonder if we want to ignore all those issues or rather keep fixing them.

Also those changes do not match the commit message.

**Comment by harshad16** [comment]
> All those "noqa" comments are coming from some IDE?
> It makes me wonder if we want to ignore all those issues or rather keep fixing them.

the noqa were for the missing docstrings in the test.  
these were added for pycqa/pydocstyle.git to ignore them for now.

we should definitely work on fixing them, I did fix it for the few.
 
> Also those changes do not match the commit message.
what would you suggest commit message to be ?

**Comment by martinpovolny** [comment]
> the noqa were for the missing docstrings in the test.

I was wondering if you are adding these by hand or if some IDE does that for you based on a linter setting or something. (I am quite new to the python ecosystem.)

> what would you suggest commit message to be ?

What about "Silence all docstring warnings." (separate commit)?

Because those changes really do not "Enable pre-commit for the application" ;-)

**Comment by harshad16** [comment]
> I was wondering if you are adding these by hand or if some IDE does that for you based on a linter setting or something. (I am quite new to the python ecosystem.)

we use [pre-commit](https://pre-commit.com/#install) framework to keep check on code linting, style maintainability and readability.
as it framework, it itself run bunch of individual test , like pydocstyle check,flakes8 checks, mypy test checks as such.
I have also update the README.md in this PR to make our contributors aware that we would be following these standards.
please do let me know if your like some more details on anything particular.

pre-commit can be executed through command line, `pre-commit run --all-files`
i have used this and fixed based upon the errors it provided.

> What about "Silence all docstring warnings." (separate commit)?
 
totally agree on this, i have updated the commit with description. 
now its
```
follow pre-commit compliance for the application
- Modified docstring based on pydocstring requirement
- silence all test docstring warnings
- followed flake8 pattern
```
let me know if you have any more suggestions.

**Comment by martinpovolny** [comment]
> let me know if you have any more suggestions.

thx, looks great

**Pull request merged**
