### PR TITLE
Replace Exception rising in PrometheusConnect class to internal one

### PR DESCRIPTION
**Pull request by lobziik**
Hi,
I suggest to replace `Exception` rising in `PrometheusConnect` to internal exception class.
Due to this changes errors handling in end-users code will be bit more obvious :)

`PrometheusApiClientException` inherited from `Exception`, so no breaking changes there

Thanks,
Denis

### CODE REVIEW

**Comment by 4n4nd** [comment]
This looks like a good suggestion :+1:

**Comment by 4n4nd** [comment]
@lobziik this looks good :+1: can you also add a test case that checks for this exception?
I think the test cases would go in [here](https://github.com/AICoE/prometheus-api-client-python/blob/master/tests/test_prometheus_connect.py)

Thanks!

**Comment by lobziik** [comment]
@4n4nd @harshad16 
https://github.com/lobziik/prometheus-api-client-python/pull/1/files could you take a look on this?
I little bit reordered tests there, added tox and mocks. Pytest style was also enforced there.

That stuff will broke your current CI settings, some changes will be required. Unfortunately I didnt figure out how it works, yet.
I also enabled travis there, might be removed.

**Comment by 4n4nd** [comment]
@lobziik Oh yes please, I have been wanting to add mock tests for so long now. This would be great, but can you divide all of these changes into smaller PRs so its easier to review?

Thanks

**Comment by lobziik** [comment]
@4n4nd I will try... But all changes there is quite tied to each other.
Btw, how you managing dependencies that needs for test runs?

**Comment by 4n4nd** [comment]
@lobziik the bots use the Pipfile to set up the testing env, so updating the pipfile and the piplock should be enough I think

**Comment by 4n4nd** [comment]
Thanks!

**Pull request merged**
