### PR TITLE
feat: replaced exit with ValueError

### PR DESCRIPTION
**Pull request by anushkrishnav**
Fixes the Issue: #79

### CODE REVIEW

**Review by 4n4nd — CHANGES_REQUESTED** [review]
Can you fix this linting error?

**Review by 4n4nd — CHANGES_REQUESTED** [review]
This looks good :+1: 
Could you also add a simple test case to check for this in [here](https://github.com/AICoE/prometheus-api-client-python/blob/master/tests/test_prometheus_connect.py#L86)?
Thanks!

**Comment by anushkrishnav** [comment]
> This looks good 
> Could you also add a simple test case to check for this in [here](https://github.com/AICoE/prometheus-api-client-python/blob/master/tests/test_prometheus_connect.py#L86)?
> Thanks!

Suree will do :)

**Comment by anushkrishnav** [comment]
@4n4nd I have added a simple test case do let me know if there is a change required

**Comment by 4n4nd** [comment]
@anushkrishnav you can run the pre-commit tests locally ([instructions](https://github.com/AICoE/prometheus-api-client-python#code-styling-and-linting)).

For the pytests, you can run them with the following command in your repo root:
`PROM_URL="http://demo.robustperception.io:9090/" pytest`

**Comment by anushkrishnav** [comment]
> @anushkrishnav you can run the pre-commit tests locally ([instructions](https://github.com/AICoE/prometheus-api-client-python#code-styling-and-linting)).
> 
> For the pytests, you can run them with the following command in your repo root:
> `PROM_URL="http://demo.robustperception.io:9090/" pytest`

Sure

**Comment by anushkrishnav** [comment]
This is what is happening when I run the pre commit
      ERROR: Command errored out with exit status 1:
       command: /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/bin/python /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmph7i7wwqm
           cwd: /tmp/pip-req-build-z8ap917n
      Complete output (16 lines):
      Traceback (most recent call last):
        File "/home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-07e2fmdl/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
          config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-07e2fmdl/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-07e2fmdl/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 5, in <module>
          assert sys.version_info >= (3, 6, 0), "black requires Python 3.6+"
      AssertionError: black requires Python 3.6+
      ----------------------------------------
    ERROR: Command errored out with exit status 1: /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/bin/python /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmph7i7wwqm Check the logs for full command output.
    
Check the log at /home/codespace/.cache/pre-commit/pre-commit.log

**Comment by anushkrishnav** [comment]
@4n4nd

**Comment by 4n4nd** [comment]
It looks like you need a newer version of Python to run the tests. You are using version 3.5 rn you need version >=3.6.
> This is what is happening when I run the pre commit
> 
>       ERROR: Command errored out with exit status 1:
> 
>        command: /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/bin/python /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmph7i7wwqm
> 
>            cwd: /tmp/pip-req-build-z8ap917n
> 
>       Complete output (16 lines):
> 
>       Traceback (most recent call last):
> 
>         File "/home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
> 
>           main()
> 
>         File "/home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
> 
>           json_out['return_val'] = hook(**hook_input['kwargs'])
> 
>         File "/home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
> 
>           return hook(config_settings)
> 
>         File "/tmp/pip-build-env-07e2fmdl/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
> 
>           config_settings, requirements=['wheel'])
> 
>         File "/tmp/pip-build-env-07e2fmdl/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
> 
>           self.run_setup()
> 
>         File "/tmp/pip-build-env-07e2fmdl/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 145, in run_setup
> 
>           exec(compile(code, __file__, 'exec'), locals())
> 
>         File "setup.py", line 5, in <module>
> 
>           assert sys.version_info >= (3, 6, 0), "black requires Python 3.6+"
> 
>       AssertionError: black requires Python 3.6+
> 
>       ----------------------------------------
> 
>     ERROR: Command errored out with exit status 1: /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/bin/python /home/codespace/.cache/pre-commit/repofyi75pb8/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmph7i7wwqm Check the logs for full command output.
> 
>     
> 
> Check the log at /home/codespace/.cache/pre-commit/pre-commit.log

**Pull request closed without merging**
